### ISSUE TITLE
Why not start with sqlite?

### ISSUE THREAD

**Issue by Antoine-lb** [n00ki/sveltekit-omakase#1]
Hello 👋
Great project, please please keep working on it, this is what the Sveltekit comunity needs.

My question: why not start with sqlite by default, and document how to connect to postgresql?

StrapiJS does this, and is great bc you can get up and running so quickly. And Drizzle supports it.

Thanks for this great work!

**Comment by n00ki** [comment]
Hi @Antoine-lb :)
I'm glad you find the project useful.
honestly, this project started as my own personal starting point for SvelteKit projects. it uses pg simply because this is the database i often use.

making the project work with SQLite should be as simple as adjusting the database schemas and switching to compatible adapters. if you're familiar with DrizzleORM, this should be a reasonably simple task.
as mentioned, this is basically my own starting point, so even though everyone is invited to use it freely, it currently lacks practically **any** onboarding features (no docs, for example). I should probably start working on it at some point, and providing some guidelines for switching DBs sounds like a good idea!

**Comment by Antoine-lb** [comment]
I get it.

You could also try making something like https://shipfa.st

Wish you the best with this project!
